version: "3"

services:
    backend:
        build: ./backend-climate-cs/
        command: uvicorn main:app
        ports:
            - 8000:8000


    frontend:
        build: ./climate-cs
        command: npm start
        ports:
            - 3000:3000
        depends_on:
            - backend
      
      
